name: Sérgio Kopplin

# utilizado em diversas tags <a>
baseurl: /

# url de base para imagens
url: http://koppl.in

# utitilizado na meta tag de compartilhamento de redes sociais
domain_name: 'http://koppl.in/'

# numero de posts por pagina
paginate: 5

# removendo do build
exclude: [README.md, vendor, Gemfile, Gemfile.lock, Rakefile]

# adicionando tag do disqus
disqus: sergiokopplin

# bio que vem no rodape dos posts
bio: 'Baterista desde sempre. Programador desde 2012. Atualmente trabalhando como Front-end Developer na Catho! Formado em Sistemas para Internet. Caçando relíquias na Internet. Morador de Nárnia e Discípulo de Cristo'

# trabalho
job_title: Desenvolvedor Front-end

# google analytics
analytics: 'UA-67821299-1'

# foto do autor
picture: '/assets/images/profile.jpg'

# textos de apoio
newer_posts: 'Posts Recentes'
older_posts: 'Posts Antigos'
title: 'Um baterista programador de Nárnia'

# url dos posts e pages para criação das coleções
permalink: /:title/

# sociais
twitter: 'koppl1n'

# compilando e minificando o sass
sass:
  style: compressed

# markdown
markdown: kramdown
highlighter: pygments

# dependências de gems
gems:
  - jemoji

# social
email: sergiokopplin@gmail.com

# keywords pra páginas estáticas
keywords:
- blog
- sergiokopplin
- Sérgio
- Kopplin
- Sérgio Kopplin
- Koppl1n
- front-end
- html
- html 5
- css
- css3
- js
- javascript
- SEO
- developer
- desenvolvedor
- nárnia
- baterista
- programação
- code
- coding

# compress configs
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  ignore:
    envs: []
