name: Sérgio Kopplin

# utilizado em diversas tags <a>
baseurl: /

# url de base para imagens
url: http://koppl.in

# utitilizado na meta tag de compartilhamento de redes sociais
domain_name: 'http://koppl.in/'

# pastas de build
destination: ./build

# numero de posts por pagina
paginate: 5

# removendo do build
exclude: [README.md, vendor, Gemfile, Gemfile.lock, Rakefile, node_modules, gulpfile.js, package.json, build, bower_components]

# bio que vem no rodape dos posts
bio: 'Baterista desde sempre. Atualmente trabalhando como Front-end Developer na Catho! Formado em Sistemas para Internet e Discípulo de Cristo'

# trabalho
job_title: Desenvolvedor Front-end

# google analytics
analytics: 'UA-67821299-1'

# foto do autor
picture: '/assets/images/profile.jpg'

# textos de apoio
newer_posts: 'Posts Recentes'
older_posts: 'Posts Antigos'
title: 'Um baterista programador de Nárnia'

# url dos posts e pages para criação das coleções
permalink: /:title/

# sociais
disqus: sergiokopplin
twitter: koppl1n
email: sergiokopplin@gmail.com
facebook: sergiokopplin
youtube: sergiokopplin
github: https://github.com/sergiokopplin/kopplin-website
githubRep: kopplin-website
githubProfile: sergiokopplin

# markdown
markdown: kramdown
highlighter: pygments

# keywords pra páginas estáticas
keywords:
- blog
- sergiokopplin
- Sérgio
- Kopplin
- Sérgio Kopplin
- Koppl1n
- front-end
- html
- html 5
- css
- css3
- js
- javascript
- SEO
- developer
- desenvolvedor
- nárnia
- baterista
- programação
- code
- coding

gems: [jekyll-paginate]
